import thinky from '../thinky';

const type = thinky.type;

const Censor = thinky.createModel('Censor', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    word       : type.string(),
    createdAt  : type.date().default(new Date()),
    editedAt   : type.date().default(new Date())
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Censor.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Censor.ensureIndex('createdAt');
Censor.ensureIndex('editedAt');

Censor.associate = () => {};

export default Censor;