import thinky from '../thinky';

const type = thinky.type;

const Information = thinky.createModel('Information', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    message    : type.string(),
    createdAt  : type.date().default(new Date()),
    editedAt   : type.date().default(new Date())
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Information.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Information.ensureIndex('createdAt');
Information.ensureIndex('editedAt');

Information.associate = () => {};

export default Information;