import thinky from '../thinky';

const type = thinky.type;

const Schedule = thinky.createModel('Schedule', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    name       : type.string(),
    location   : type.string(),
    start      : Date,
    end        : Date,
    createdAt  : type.date().default(new Date()),
    editedAt   : Date,
    isRemoved  : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Schedule.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Schedule.ensureIndex('createdAt');
Schedule.ensureIndex('editedAt');

Schedule.associate = () => {};

export default Schedule;